version: "3"

vars:
  BINARY_BUILD_DIR: build/bin
  CLI_BINARY: ldfctl
  SRV_BINARY: ldfd
  WEBUI_DIR: src/webui
  # Version components
  RELEASE_NAME: Basilisk
  RELEASE_VERSION: 1.2.7
  RELEASE_DATE:
    sh: date -u +"%Y.%m"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  # Full version string: Phoenix (2025.12) - v1.0.0-4f9f297
  VERSION_STRING: "{{.RELEASE_NAME}} ({{.RELEASE_DATE}}) - v{{.RELEASE_VERSION}}-{{.GIT_COMMIT}}"
  # Server ldflags
  LDFLAGS_SRV_PROD: -ldflags "-s -w -X 'github.com/bitswalk/ldf/src/ldfd/core.Version={{.VERSION_STRING}}' -X github.com/bitswalk/ldf/src/ldfd/core.BuildDate={{.BUILD_DATE}} -X github.com/bitswalk/ldf/src/ldfd/core.GitCommit={{.GIT_COMMIT}} -X github.com/bitswalk/ldf/src/ldfd/core.ReleaseName={{.RELEASE_NAME}} -X github.com/bitswalk/ldf/src/ldfd/core.ReleaseVersion={{.RELEASE_VERSION}}"
  LDFLAGS_SRV_DEV: -ldflags "-X 'github.com/bitswalk/ldf/src/ldfd/core.Version=dev' -X github.com/bitswalk/ldf/src/ldfd/core.BuildDate=unknown"
  # CLI ldflags
  LDFLAGS_CLI_PROD: -ldflags "-s -w -X 'github.com/bitswalk/ldf/src/ldfctl/internal/cmd.Version={{.VERSION_STRING}}' -X github.com/bitswalk/ldf/src/ldfctl/internal/cmd.BuildDate={{.BUILD_DATE}} -X github.com/bitswalk/ldf/src/ldfctl/internal/cmd.GitCommit={{.GIT_COMMIT}} -X github.com/bitswalk/ldf/src/ldfctl/internal/cmd.ReleaseName={{.RELEASE_NAME}} -X github.com/bitswalk/ldf/src/ldfctl/internal/cmd.ReleaseVersion={{.RELEASE_VERSION}}"
  LDFLAGS_CLI_DEV: -ldflags "-X 'github.com/bitswalk/ldf/src/ldfctl/internal/cmd.Version=dev' -X github.com/bitswalk/ldf/src/ldfctl/internal/cmd.BuildDate=unknown"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build all (server, CLI, and WebUI) for production
    deps: [build:srv, build:cli, build:webui]

  build:dev:
    desc: Build all for development
    deps: [build:srv:dev, build:cli:dev, build:webui]

  build:cli:
    desc: Build CLI binary (production)
    cmds:
      - mkdir -p {{.BINARY_BUILD_DIR}}
      - go build {{.LDFLAGS_CLI_PROD}} -o {{.BINARY_BUILD_DIR}}/{{.CLI_BINARY}} ./src/ldfctl

  build:cli:dev:
    desc: Build CLI binary (development)
    cmds:
      - mkdir -p {{.BINARY_BUILD_DIR}}
      - go build {{.LDFLAGS_CLI_DEV}} -o {{.BINARY_BUILD_DIR}}/{{.CLI_BINARY}} ./src/ldfctl

  build:srv:
    desc: Build server binary (production)
    cmds:
      - mkdir -p {{.BINARY_BUILD_DIR}}
      - go build {{.LDFLAGS_SRV_PROD}} -o {{.BINARY_BUILD_DIR}}/{{.SRV_BINARY}} ./src/ldfd

  build:srv:dev:
    desc: Build server binary (development)
    cmds:
      - mkdir -p {{.BINARY_BUILD_DIR}}
      - go build {{.LDFLAGS_SRV_DEV}} -o {{.BINARY_BUILD_DIR}}/{{.SRV_BINARY}} ./src/ldfd

  build:webui:
    desc: Build WebUI
    dir: "{{.WEBUI_DIR}}"
    cmds:
      - bun install --frozen-lockfile
      - bun run build

  build:webui:dev:
    desc: Start WebUI dev server
    dir: "{{.WEBUI_DIR}}"
    cmds:
      - bun install
      - bun run dev

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BINARY_BUILD_DIR}}
      - rm -rf {{.WEBUI_DIR}}/dist
      - go clean

  test:
    desc: Run all tests
    deps: [test:srv, test:cli, test:webui]

  test:srv:
    desc: Run server tests
    cmds:
      - go test -v ./src/ldfd/...

  test:cli:
    desc: Run CLI tests
    cmds:
      - go test -v ./src/ldfctl/...

  test:webui:
    desc: Run WebUI tests
    dir: "{{.WEBUI_DIR}}"
    cmds:
      - bun run test

  run:srv:
    desc: Run server (production build)
    deps: [build:srv]
    cmds:
      - ./{{.BINARY_BUILD_DIR}}/{{.SRV_BINARY}}

  run:srv:dev:
    desc: Run server in development mode
    deps: [build:srv:dev]
    cmds:
      - ./{{.BINARY_BUILD_DIR}}/{{.SRV_BINARY}} --log-output stdout --log-level debug

  deps:
    desc: Download Go dependencies
    cmds:
      - go mod download
      - go mod tidy

  deps:webui:
    desc: Install WebUI dependencies
    dir: "{{.WEBUI_DIR}}"
    cmds:
      - bun install

  docs:api:
    desc: Generate OpenAPI spec from annotations
    cmds:
      - swag init --dir src/ldfd,src/common -g docs.go -o src/ldfd/docs --parseDependency --parseInternal

  fmt:
    desc: Format code
    cmds:
      - go fmt ./src/...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./src/...
